### PR TITLE
Autogenerate about dialog from authors file

### PR DESCRIPTION
**Pull request by dffischer**
This generates [abraca-about.ui](src/resources/ui/abraca-about.ui) from [AUTHORS](AUTHORS) via [a waf tool](waftools/about-generator.py).

### CODE REVIEW

**Comment by dsvensson** [comment]
Awesome! I was only thinking out loud wrt the auto-generated part, thanks for fixing it!

**Comment by dsvensson** [comment]
Bleh.. should have tested it straight away when I wrote the above comment. Finally took the time to try it out, but it's unfortunately failing with:

```
$ ./waf build
Waf: Entering directory `/home/daniel/Development/home/Abraca/build'
Waf: Leaving directory `/home/daniel/Development/home/Abraca/build'
Traceback (most recent call last):
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Scripting.py", line 351, in execute
    return execute_method(self)
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 106, in execute
    self.execute_build()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 115, in execute_build
    self.compile()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 190, in compile
    self.producer.start()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Runner.py", line 149, in start
    self.refill_task_list()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Runner.py", line 98, in refill_task_list
    self.outstanding.extend(self.biter.next())
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 420, in get_build_iterator
    self.post_group()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/Build.py", line 404, in post_group
    f()
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/TaskGen.py", line 109, in post
    v()
  File "waftools/about-generator.py", line 117, in authors_template
    gen.create_task('template', [authors, template], target)
  File "/home/daniel/Development/home/Abraca/.waf-1.7.6-aeca75c39c28caac64540ecaf32d4f82/waflib/TaskGen.py", line 122, in create_task
    task=Task.classes[name](env=self.env.derive(),generator=self)
  File "waftools/about-generator.py", line 85, in __init__
    super().__init__(*k, **kw)
TypeError: super() takes at least 1 argument (0 given)
```

Using Python 2.7 here.

**Comment by dffischer** [comment]
It should now also work with Python 2.7.

**Comment by dsvensson** [comment]
Since I hadn't written any best practices document wrt git before you sent this pull requestI took the liberty of restructuring your history to make it easier to review:

https://github.com/Abraca/Abraca/compare/autogen-about

I've also added the beginnings of a coding style and git best practices document at the main wiki:
https://github.com/Abraca/Abraca/wiki

If everything looks fine to you in my restructured branch I'd be happy to merge it.

**Comment by dffischer** [comment]
So macrocommits they shall be.

Looks like everything is okay with it. Builds and executes cleanly here.

The style definitions are concise and quick to capture.

**Comment by dsvensson** [comment]
Well.. macro and macro. Just squashing together the commits that move new functionality from A->B->C->D so that they go straight from A->D instead. Commits splits based on functionality separation, it's no use keeping the thought path and errors from first attempt until it finally works. Thanks for your effort!

**Pull request closed without merging**
